language: php
php:
  - 5.5
  - 5.6
  - 5.5
  - 7
  - hhvm
install: composer install
script: ./vendor/bin/phpunit 
after_success: 
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" -a "$TRAVIS_PHP_VERSION" != "7" ]; then bash <(curl -s https://codecov.io/bash); fi'
matrix:
  fast_finish: true
  allow_failures:
     - php: 7
     - php: hhvm
